// See https://aka.ms/new-console-template for more information

using ConsoleApp1;

Console.WriteLine("Hello, World!");
Phone phone1 = Creator.RandomPhone();
Phone phone2 = Creator.RandomPhone();
Phone phone3 = Creator.RandomPhone();
Phone phone4 = Creator.RandomPhone();
Phone phone5 = Creator.RandomPhone();
List<Phone> phones = new List<Phone>();
phones.Add(phone1);
phones.Add(phone2);
phones.Add(phone3);
phones.Add(phone4);
phones.Add(phone5);
phones.ForEach(Console.WriteLine);
Console.WriteLine("Task1");
var phoneNumber = phones.Count;
Console.WriteLine(phoneNumber);
Console.WriteLine("Task2");
var phonePrice = phones.Where(p => p.Price > 100).Count();
Console.WriteLine(phonePrice);
Console.WriteLine("Task3");
var phonePriceDiapazon = phones.Where(p => p.Price >= 400 && p.Price<=700).Count();
Console.WriteLine(phonePriceDiapazon);
Console.WriteLine("Task4");
var phoneCountOfApple = phones.Where(p => p.Company == "Apple").Count();
Console.WriteLine(phoneCountOfApple);
Console.WriteLine("Task5");
var phoneThatHasMaxPrice = phones.OrderByDescending(p => p.Price).First();
Console.WriteLine(phoneThatHasMaxPrice);
Console.WriteLine("Task6");
var phoneThatHasLowestPrice = phones.OrderBy(p => p.Price).First();
Console.WriteLine(phoneThatHasLowestPrice);
Console.WriteLine("Task7");
var phoneThatIsOldest = phones.OrderBy(p => p.DateOfRelease).First();
Console.WriteLine(phoneThatIsOldest);
Console.WriteLine("Task8");
var phoneThatIsNewest = phones.OrderByDescending(p => p.DateOfRelease).First();
Console.WriteLine(phoneThatIsNewest);
Console.WriteLine("Task9");
var phoneMidPrice = phones.OrderByDescending(p => p.Price).Average(p=>p.Price);
Console.WriteLine(phoneMidPrice);
Console.WriteLine("Task10"); 
var top5PhonesHighest = phones.OrderByDescending(p => p.Price).Take(5).ToList();
top5PhonesHighest.ForEach(Console.WriteLine);
Console.WriteLine("Task11");
var top5PhoneLowest = phones.OrderBy(p => p.Price).Take(5).ToList();
top5PhoneLowest.ForEach(Console.WriteLine);
Console.WriteLine("Task12");
var top3Oldest = phones.OrderBy(p => p.DateOfRelease).Take(3).ToList();
top3Oldest.ForEach(Console.WriteLine);
Console.WriteLine("Task13");
var top3Newest = phones.OrderByDescending(p => p.DateOfRelease).Take(3).ToList();
top3Newest.ForEach(Console.WriteLine);
Console.WriteLine("Task14");
var countOfCompanyPhones =  phones.GroupBy(p=>p.Company).Select(g=>new{Company =g.Key,Count=g.Count()}).ToList();
countOfCompanyPhones.ForEach(Console.WriteLine);
Console.WriteLine("Task15");
var countOfNamePhones = phones.GroupBy(p=>p.PhoneName).Select(g=>new{PhoneName=g.Key,Count=g.Count()}).ToList();
countOfNamePhones.ForEach(Console.WriteLine);
Console.WriteLine("Task16");
var countOfPhoneByYear = phones.GroupBy(p=>p.DateOfRelease.Year).Select(g => new{DateOfRelease=g.Key,Count=g.Count()}).ToList();
countOfPhoneByYear.ForEach(Console.WriteLine);
;